import React, { useMemo, useState } from "react";
import { useStore } from "../store/useStore";
import { Prism as SyntaxHighlighter } from "react-syntax-highlighter";
import { vscDarkPlus } from "react-syntax-highlighter/dist/esm/styles/prism";
import JSZip from "jszip";
import { saveAs } from "file-saver";

/**
 * ExportPanel
 * - generates a React component string from current blocks
 * - preview with syntax highlighter
 * - copy to clipboard, download .jsx, download zip
 */

function escapeTextForJSX(text) {
  if (text == null) return "";
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/`/g, "\\`");
}

function generateReactComponentCode(blocks, componentName = "CanvasExport") {
  // Build JSX for blocks with inline styles
  const children = blocks
    .map((b) => {
      // safe text
      const safeText = escapeTextForJSX(String(b.text || ""));
      const style = {
        position: "absolute",
        left: `${b.x}px`,
        top: `${b.y}px`,
        width: `${b.width}px`,
        height: `${b.height}px`,
        boxSizing: "border-box",
        borderRadius: "8px",
        background: "#ffffff",
        border: "1px solid #e5e7eb",
        padding: "12px",
        overflow: "hidden",
      };

      // stringify style object for inline style in JS
      const styleString = Object.entries(style)
        .map(([k, v]) => {
          // convert camelCase to JS style key (keep camelCase)
          return `${k.replace(/-([a-z])/g, (_, chr) => chr.toUpperCase())}: "${v}"`;
        })
        .join(", ");

      return `  <div key="${b.id}" style={{ ${styleString} }}>
    ${safeText}
  </div>`;
    })
    .join("\n\n");

  // full component
  const code = `import React from "react";

/**
 * ${componentName} — exported from Generative UI Composer
 * This component uses inline styles for layout so it can be dropped into any React app.
 */

export default function ${componentName}() {
  return (
    <div style={{
      position: "relative",
      width: "100%",
      minHeight: "400px",
      background: "linear-gradient(180deg, #f8fafc 0%, #f1f5f9 100%)",
      padding: "24px",
      boxSizing: "border-box"
    }}>
${children ? "\n" + children + "\n" : ""}
    </div>
  );
}
`;

  return code;
}

export default function ExportPanel() {
  const blocks = useStore((s) => s.blocks);
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);

  const code = useMemo(() => generateReactComponentCode(blocks, "CanvasExport"), [blocks]);

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 1600);
    } catch (err) {
      console.error("Clipboard failed", err);
      alert("Copy failed. Your browser may block clipboard access.");
    }
  }

  function downloadJSX() {
    const blob = new Blob([code], { type: "text/plain;charset=utf-8" });
    saveAs(blob, "CanvasExport.jsx");
  }

  async function downloadZip() {
    setDownloading(true);
    try {
      const zip = new JSZip();
      zip.file("CanvasExport.jsx", code);

      // optional: add README
      zip.file(
        "README.md",
        `# CanvasExport\n\nThis ZIP contains CanvasExport.jsx generated by Generative UI Composer.\n\nDrop CanvasExport.jsx into your React app and import it.\n`
      );

      const content = await zip.generateAsync({ type: "blob" });
      saveAs(content, "canvas-export.zip");
    } catch (err) {
      console.error(err);
      alert("Failed to create zip.");
    } finally {
      setDownloading(false);
    }
  }

  return (
    <aside className="w-[520px] border-l bg-white p-4 flex flex-col">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold">Export</h3>
        <div className="text-sm text-slate-500">Generate React component</div>
      </div>

      <div className="mt-3 text-sm text-slate-600">
        Generates a self-contained React component (JSX with inline styles). You can copy, download, or download a ZIP.
      </div>

      <div className="mt-3 flex gap-2">
        <button onClick={copyToClipboard} className="px-3 py-2 rounded bg-sky-600 text-white text-sm">
          {copied ? "Copied!" : "Copy code"}
        </button>

        <button onClick={downloadJSX} className="px-3 py-2 rounded bg-emerald-600 text-white text-sm">
          Download .jsx
        </button>

        <button onClick={downloadZip} className="px-3 py-2 rounded bg-slate-100 text-sm">
          {downloading ? "Preparing..." : "Download ZIP"}
        </button>
      </div>

      <div className="mt-4 flex-1 overflow-auto border rounded">
        <SyntaxHighlighter language="jsx" style={vscDarkPlus} wrapLongLines customStyle={{ margin: 0, borderRadius: 6 }}>
          {code}
        </SyntaxHighlighter>
      </div>
    </aside>
  );
}
